name: Test Next App
on: 
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: bun install
      - name: Test application
        run: bun run test
